<?php
/**
 * @file sendgrid_integratin.install
 * Main module file for SendGrid Integration.
 *
 * Provides module configuration and help functionality.
 */


/**
 * Implements hook_menu().
 */
function sendgrid_integration_menu() {
  $items = array();

  $items['admin/config/system/sendgrid'] = array(
    'title' => 'SendGrid settings',
    'description' => 'SendGrid Integration settings',
    'page callback' =>'drupal_get_form',
    'page arguments' => array('sendgrid_integration_admin'),
    'access callback' => 'user_access',
    'access arguments' => array('Administer SendGrid settings'),
  );

  return $items;
}

/**
 * Implements hook_permissions().
 */
function sendgrid_integration_permissions() {
  return array(
    'title' => t('Administer SendGrid settings'),
    'description' => t('Configure SendGrid options like username and password'),
  );
}

/**
 * Provides Settings Form.
 */
function sendgrid_integration_admin() {
  $form = array();

  $form['authentication'] = array(
    '#type' => 'fieldset',
    '#title' => t('Authentication'),
  );

  $form['authentication']['sendgrid_integration_username'] = array(
    '#type' => 'textfield',
    '#title' => t('Username'),
    '#description' => t('Your SendGrid Username'),
    '#required' => TRUE,
    '#default_value' => variable_get('sendgrid_integration_username', ''),
  );

  $form['authentication']['sendgrid_integration_apikey'] = array(
    '#type' => 'password',
    '#title' => t('API Key'),
    '#description' => t('Your SendGrid Password'),
    '#required' => TRUE,
    '#default_value' => variable_get('sendgrid_integration_apikey', ''),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_help().
 */
function sendgrid_integration_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#sendgrid_integration':
      $output .= '<h3>' . t('SendGrid Integration') . '</h3>';
      $output .= '<p>' . t('Module provides own implementation of MailSystemIntegration, replacing the default implementation and uses SendGrid Web API instead.') . '</p>';
  }
  return $output;
}
